// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brpc/policy/sofa_pbrpc_meta.proto

#ifndef PROTOBUF_brpc_2fpolicy_2fsofa_5fpbrpc_5fmeta_2eproto__INCLUDED
#define PROTOBUF_brpc_2fpolicy_2fsofa_5fpbrpc_5fmeta_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace brpc {
namespace policy {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_brpc_2fpolicy_2fsofa_5fpbrpc_5fmeta_2eproto();
void protobuf_AssignDesc_brpc_2fpolicy_2fsofa_5fpbrpc_5fmeta_2eproto();
void protobuf_ShutdownFile_brpc_2fpolicy_2fsofa_5fpbrpc_5fmeta_2eproto();

class SofaRpcMeta;

enum SofaRpcMeta_Type {
  SofaRpcMeta_Type_REQUEST = 0,
  SofaRpcMeta_Type_RESPONSE = 1
};
bool SofaRpcMeta_Type_IsValid(int value);
const SofaRpcMeta_Type SofaRpcMeta_Type_Type_MIN = SofaRpcMeta_Type_REQUEST;
const SofaRpcMeta_Type SofaRpcMeta_Type_Type_MAX = SofaRpcMeta_Type_RESPONSE;
const int SofaRpcMeta_Type_Type_ARRAYSIZE = SofaRpcMeta_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* SofaRpcMeta_Type_descriptor();
inline const ::std::string& SofaRpcMeta_Type_Name(SofaRpcMeta_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    SofaRpcMeta_Type_descriptor(), value);
}
inline bool SofaRpcMeta_Type_Parse(
    const ::std::string& name, SofaRpcMeta_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SofaRpcMeta_Type>(
    SofaRpcMeta_Type_descriptor(), name, value);
}
enum SofaCompressType {
  SOFA_COMPRESS_TYPE_NONE = 0,
  SOFA_COMPRESS_TYPE_GZIP = 1,
  SOFA_COMPRESS_TYPE_ZLIB = 2,
  SOFA_COMPRESS_TYPE_SNAPPY = 3,
  SOFA_COMPRESS_TYPE_LZ4 = 4
};
bool SofaCompressType_IsValid(int value);
const SofaCompressType SofaCompressType_MIN = SOFA_COMPRESS_TYPE_NONE;
const SofaCompressType SofaCompressType_MAX = SOFA_COMPRESS_TYPE_LZ4;
const int SofaCompressType_ARRAYSIZE = SofaCompressType_MAX + 1;

const ::google::protobuf::EnumDescriptor* SofaCompressType_descriptor();
inline const ::std::string& SofaCompressType_Name(SofaCompressType value) {
  return ::google::protobuf::internal::NameOfEnum(
    SofaCompressType_descriptor(), value);
}
inline bool SofaCompressType_Parse(
    const ::std::string& name, SofaCompressType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SofaCompressType>(
    SofaCompressType_descriptor(), name, value);
}
// ===================================================================

class SofaRpcMeta : public ::google::protobuf::Message {
 public:
  SofaRpcMeta();
  virtual ~SofaRpcMeta();

  SofaRpcMeta(const SofaRpcMeta& from);

  inline SofaRpcMeta& operator=(const SofaRpcMeta& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SofaRpcMeta& default_instance();

  void Swap(SofaRpcMeta* other);

  // implements Message ----------------------------------------------

  SofaRpcMeta* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SofaRpcMeta& from);
  void MergeFrom(const SofaRpcMeta& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef SofaRpcMeta_Type Type;
  static const Type REQUEST = SofaRpcMeta_Type_REQUEST;
  static const Type RESPONSE = SofaRpcMeta_Type_RESPONSE;
  static inline bool Type_IsValid(int value) {
    return SofaRpcMeta_Type_IsValid(value);
  }
  static const Type Type_MIN =
    SofaRpcMeta_Type_Type_MIN;
  static const Type Type_MAX =
    SofaRpcMeta_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    SofaRpcMeta_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return SofaRpcMeta_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return SofaRpcMeta_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return SofaRpcMeta_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .brpc.policy.SofaRpcMeta.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::brpc::policy::SofaRpcMeta_Type type() const;
  inline void set_type(::brpc::policy::SofaRpcMeta_Type value);

  // required uint64 sequence_id = 2;
  inline bool has_sequence_id() const;
  inline void clear_sequence_id();
  static const int kSequenceIdFieldNumber = 2;
  inline ::google::protobuf::uint64 sequence_id() const;
  inline void set_sequence_id(::google::protobuf::uint64 value);

  // optional string method = 100;
  inline bool has_method() const;
  inline void clear_method();
  static const int kMethodFieldNumber = 100;
  inline const ::std::string& method() const;
  inline void set_method(const ::std::string& value);
  inline void set_method(const char* value);
  inline void set_method(const char* value, size_t size);
  inline ::std::string* mutable_method();
  inline ::std::string* release_method();
  inline void set_allocated_method(::std::string* method);

  // optional bool failed = 200;
  inline bool has_failed() const;
  inline void clear_failed();
  static const int kFailedFieldNumber = 200;
  inline bool failed() const;
  inline void set_failed(bool value);

  // optional int32 error_code = 201;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 201;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);

  // optional string reason = 202;
  inline bool has_reason() const;
  inline void clear_reason();
  static const int kReasonFieldNumber = 202;
  inline const ::std::string& reason() const;
  inline void set_reason(const ::std::string& value);
  inline void set_reason(const char* value);
  inline void set_reason(const char* value, size_t size);
  inline ::std::string* mutable_reason();
  inline ::std::string* release_reason();
  inline void set_allocated_reason(::std::string* reason);

  // optional .brpc.policy.SofaCompressType compress_type = 300;
  inline bool has_compress_type() const;
  inline void clear_compress_type();
  static const int kCompressTypeFieldNumber = 300;
  inline ::brpc::policy::SofaCompressType compress_type() const;
  inline void set_compress_type(::brpc::policy::SofaCompressType value);

  // optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;
  inline bool has_expected_response_compress_type() const;
  inline void clear_expected_response_compress_type();
  static const int kExpectedResponseCompressTypeFieldNumber = 301;
  inline ::brpc::policy::SofaCompressType expected_response_compress_type() const;
  inline void set_expected_response_compress_type(::brpc::policy::SofaCompressType value);

  // @@protoc_insertion_point(class_scope:brpc.policy.SofaRpcMeta)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_sequence_id();
  inline void clear_has_sequence_id();
  inline void set_has_method();
  inline void clear_has_method();
  inline void set_has_failed();
  inline void clear_has_failed();
  inline void set_has_error_code();
  inline void clear_has_error_code();
  inline void set_has_reason();
  inline void clear_has_reason();
  inline void set_has_compress_type();
  inline void clear_has_compress_type();
  inline void set_has_expected_response_compress_type();
  inline void clear_has_expected_response_compress_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 sequence_id_;
  int type_;
  bool failed_;
  ::std::string* method_;
  ::std::string* reason_;
  ::google::protobuf::int32 error_code_;
  int compress_type_;
  int expected_response_compress_type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];

  friend void  protobuf_AddDesc_brpc_2fpolicy_2fsofa_5fpbrpc_5fmeta_2eproto();
  friend void protobuf_AssignDesc_brpc_2fpolicy_2fsofa_5fpbrpc_5fmeta_2eproto();
  friend void protobuf_ShutdownFile_brpc_2fpolicy_2fsofa_5fpbrpc_5fmeta_2eproto();

  void InitAsDefaultInstance();
  static SofaRpcMeta* default_instance_;
};
// ===================================================================


// ===================================================================

// SofaRpcMeta

// required .brpc.policy.SofaRpcMeta.Type type = 1;
inline bool SofaRpcMeta::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SofaRpcMeta::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SofaRpcMeta::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SofaRpcMeta::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::brpc::policy::SofaRpcMeta_Type SofaRpcMeta::type() const {
  return static_cast< ::brpc::policy::SofaRpcMeta_Type >(type_);
}
inline void SofaRpcMeta::set_type(::brpc::policy::SofaRpcMeta_Type value) {
  assert(::brpc::policy::SofaRpcMeta_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// required uint64 sequence_id = 2;
inline bool SofaRpcMeta::has_sequence_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SofaRpcMeta::set_has_sequence_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SofaRpcMeta::clear_has_sequence_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SofaRpcMeta::clear_sequence_id() {
  sequence_id_ = GOOGLE_ULONGLONG(0);
  clear_has_sequence_id();
}
inline ::google::protobuf::uint64 SofaRpcMeta::sequence_id() const {
  return sequence_id_;
}
inline void SofaRpcMeta::set_sequence_id(::google::protobuf::uint64 value) {
  set_has_sequence_id();
  sequence_id_ = value;
}

// optional string method = 100;
inline bool SofaRpcMeta::has_method() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SofaRpcMeta::set_has_method() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SofaRpcMeta::clear_has_method() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SofaRpcMeta::clear_method() {
  if (method_ != &::google::protobuf::internal::kEmptyString) {
    method_->clear();
  }
  clear_has_method();
}
inline const ::std::string& SofaRpcMeta::method() const {
  return *method_;
}
inline void SofaRpcMeta::set_method(const ::std::string& value) {
  set_has_method();
  if (method_ == &::google::protobuf::internal::kEmptyString) {
    method_ = new ::std::string;
  }
  method_->assign(value);
}
inline void SofaRpcMeta::set_method(const char* value) {
  set_has_method();
  if (method_ == &::google::protobuf::internal::kEmptyString) {
    method_ = new ::std::string;
  }
  method_->assign(value);
}
inline void SofaRpcMeta::set_method(const char* value, size_t size) {
  set_has_method();
  if (method_ == &::google::protobuf::internal::kEmptyString) {
    method_ = new ::std::string;
  }
  method_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SofaRpcMeta::mutable_method() {
  set_has_method();
  if (method_ == &::google::protobuf::internal::kEmptyString) {
    method_ = new ::std::string;
  }
  return method_;
}
inline ::std::string* SofaRpcMeta::release_method() {
  clear_has_method();
  if (method_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = method_;
    method_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void SofaRpcMeta::set_allocated_method(::std::string* method) {
  if (method_ != &::google::protobuf::internal::kEmptyString) {
    delete method_;
  }
  if (method) {
    set_has_method();
    method_ = method;
  } else {
    clear_has_method();
    method_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bool failed = 200;
inline bool SofaRpcMeta::has_failed() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SofaRpcMeta::set_has_failed() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SofaRpcMeta::clear_has_failed() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SofaRpcMeta::clear_failed() {
  failed_ = false;
  clear_has_failed();
}
inline bool SofaRpcMeta::failed() const {
  return failed_;
}
inline void SofaRpcMeta::set_failed(bool value) {
  set_has_failed();
  failed_ = value;
}

// optional int32 error_code = 201;
inline bool SofaRpcMeta::has_error_code() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SofaRpcMeta::set_has_error_code() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SofaRpcMeta::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SofaRpcMeta::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 SofaRpcMeta::error_code() const {
  return error_code_;
}
inline void SofaRpcMeta::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// optional string reason = 202;
inline bool SofaRpcMeta::has_reason() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SofaRpcMeta::set_has_reason() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SofaRpcMeta::clear_has_reason() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SofaRpcMeta::clear_reason() {
  if (reason_ != &::google::protobuf::internal::kEmptyString) {
    reason_->clear();
  }
  clear_has_reason();
}
inline const ::std::string& SofaRpcMeta::reason() const {
  return *reason_;
}
inline void SofaRpcMeta::set_reason(const ::std::string& value) {
  set_has_reason();
  if (reason_ == &::google::protobuf::internal::kEmptyString) {
    reason_ = new ::std::string;
  }
  reason_->assign(value);
}
inline void SofaRpcMeta::set_reason(const char* value) {
  set_has_reason();
  if (reason_ == &::google::protobuf::internal::kEmptyString) {
    reason_ = new ::std::string;
  }
  reason_->assign(value);
}
inline void SofaRpcMeta::set_reason(const char* value, size_t size) {
  set_has_reason();
  if (reason_ == &::google::protobuf::internal::kEmptyString) {
    reason_ = new ::std::string;
  }
  reason_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SofaRpcMeta::mutable_reason() {
  set_has_reason();
  if (reason_ == &::google::protobuf::internal::kEmptyString) {
    reason_ = new ::std::string;
  }
  return reason_;
}
inline ::std::string* SofaRpcMeta::release_reason() {
  clear_has_reason();
  if (reason_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = reason_;
    reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void SofaRpcMeta::set_allocated_reason(::std::string* reason) {
  if (reason_ != &::google::protobuf::internal::kEmptyString) {
    delete reason_;
  }
  if (reason) {
    set_has_reason();
    reason_ = reason;
  } else {
    clear_has_reason();
    reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .brpc.policy.SofaCompressType compress_type = 300;
inline bool SofaRpcMeta::has_compress_type() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SofaRpcMeta::set_has_compress_type() {
  _has_bits_[0] |= 0x00000040u;
}
inline void SofaRpcMeta::clear_has_compress_type() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void SofaRpcMeta::clear_compress_type() {
  compress_type_ = 0;
  clear_has_compress_type();
}
inline ::brpc::policy::SofaCompressType SofaRpcMeta::compress_type() const {
  return static_cast< ::brpc::policy::SofaCompressType >(compress_type_);
}
inline void SofaRpcMeta::set_compress_type(::brpc::policy::SofaCompressType value) {
  assert(::brpc::policy::SofaCompressType_IsValid(value));
  set_has_compress_type();
  compress_type_ = value;
}

// optional .brpc.policy.SofaCompressType expected_response_compress_type = 301;
inline bool SofaRpcMeta::has_expected_response_compress_type() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void SofaRpcMeta::set_has_expected_response_compress_type() {
  _has_bits_[0] |= 0x00000080u;
}
inline void SofaRpcMeta::clear_has_expected_response_compress_type() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void SofaRpcMeta::clear_expected_response_compress_type() {
  expected_response_compress_type_ = 0;
  clear_has_expected_response_compress_type();
}
inline ::brpc::policy::SofaCompressType SofaRpcMeta::expected_response_compress_type() const {
  return static_cast< ::brpc::policy::SofaCompressType >(expected_response_compress_type_);
}
inline void SofaRpcMeta::set_expected_response_compress_type(::brpc::policy::SofaCompressType value) {
  assert(::brpc::policy::SofaCompressType_IsValid(value));
  set_has_expected_response_compress_type();
  expected_response_compress_type_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace policy
}  // namespace brpc

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::brpc::policy::SofaRpcMeta_Type>() {
  return ::brpc::policy::SofaRpcMeta_Type_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::brpc::policy::SofaCompressType>() {
  return ::brpc::policy::SofaCompressType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_brpc_2fpolicy_2fsofa_5fpbrpc_5fmeta_2eproto__INCLUDED
